Fix: changed workflow flow

diff --git a/.github/workflows/build_test_scan.yml b/.github/workflows/build_test_scan.yml
--- a/.github/workflows/build_test_scan.yml
+++ b/.github/workflows/build_test_scan.yml
@@ -6,6 +6,11 @@ on:
       - main
   workflow_dispatch:
 
+env:
+  SCAN_VALID: 'false'
+  SCAN_RESULT: ''
+
+
 jobs:
   build-test:
     runs-on: ubuntu-latest
@@ -183,7 +188,7 @@ jobs:
 
   evaluate_scanning_results:
     needs: [build-test, sast, dast1, dast2, secret_scan, dependency_scan]
-    if: always() && github.event_name == 'pull_request'
+    if: always()
     runs-on: ubuntu-latest
 
     steps:
@@ -220,6 +225,19 @@ jobs:
 
       - run: python3 .github/workflows/result_validation.py
 
+      - name: Fail workflow if scan is invalid
+        if: ${{ env.SCAN_VALID == 'False' }}
+        run: |
+          echo "The security scan was not valid. Failing the workflow."
+          exit 1
+          
+
+  scanning_result_pr:
+    runs-on: ubuntu-latest
+    needs: [evaluate_scanning_results]
+    if: always() && github.event_name == 'pull_request'
+
+    steps:
       - name: Comment PR positive
         if: ${{ env.SCAN_VALID == 'True' }}
         uses: peter-evans/create-or-update-comment@v4.0.0
@@ -236,9 +254,3 @@ jobs:
           token: ${{ secrets.GITHUB_TOKEN }}
           issue-number: ${{ github.event.pull_request.number }}
           body: "The security scan was not valid. ${{ env.SCAN_RESULT }}"
-
-      - name: Fail workflow if scan is invalid
-        if: ${{ env.SCAN_VALID == 'False' }}
-        run: |
-          echo "The security scan was not valid. Failing the workflow."
-          exit 1
